package org.example.cluster

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.launch
import org.example.commands.Command
import org.example.engine.BalanceService
import org.example.engine.TradingEngine
import org.example.events.Event
import org.example.store.EventStore
import org.example.store.InMemoryEventStore
import org.example.store.FilePersistence
import org.example.query.QuerySide
import org.slf4j.LoggerFactory

enum class NodeRole { LEADER, FOLLOWER }

class ClusterNode(
    val nodeId: String,
    private val scope: CoroutineScope
) {
    private val logger = LoggerFactory.getLogger("Node-$nodeId")
    var role = NodeRole.FOLLOWER
    val eventStore: EventStore = InMemoryEventStore()
    val balanceService = BalanceService()
    val tradingEngine = TradingEngine(eventStore, balanceService, scope)
    val querySide = QuerySide(eventStore, scope)
    
    private val replicationChannel = Channel<List<Event>>(Channel.BUFFERED)
    private var peers: List<ClusterNode> = emptyList()

    init {
        scope.launch {
            val persistence = FilePersistence("events-${nodeId}.log", scope)
            eventStore.subscribePersistence(persistence)
        }

        scope.launch {
            for (events in replicationChannel) {
                if (role == NodeRole.FOLLOWER) {
                    eventStore.appendReplicated(events)
                }
            }
        }
        
        // Keep local state in sync
        scope.launch {
            eventStore.allEvents().collect { event ->
                // Apply to local state if not already applied by MatchingActor
                // To avoid double application, BalanceService and OrderBook should be idempotent 
                // (they are, mostly, based on eventId)
                // Actually, MatchingActor already applies events it generates.
                // But it doesn't apply events generated by others (replicated) or initial ones.
                // So we apply here.
                balanceService.applyEvent(event)
            }
        }
    }

    suspend fun processCommand(command: Command): Boolean {
        if (role != NodeRole.LEADER) {
            return false
        }
        
        val result = tradingEngine.process(command)
        
        if (result) {
            // Replication is triggered by the EventStore subscription or manually
            // Let's subscribe to local event store to replicate everything
        }
        
        return result
    }

    fun setPeers(nodes: List<ClusterNode>) {
        this.peers = nodes
    }

    suspend fun startReplicationLoop() {
        eventStore.allEvents().collect { event ->
            if (role == NodeRole.LEADER) {
                peers.forEach { peer ->
                    peer.replicationChannel.send(listOf(event))
                }
            }
        }
    }
}
